### ISSUE TITLE
API documentation e-delivery

### ISSUE THREAD

**Issue by Vishant0031** [sovos-foriba-rd/cloud_sample_api_client_dotnet#1]
I can find API doc for e-invoice, e-archive etc....
Is there API documentation about e-delivery note?
I also learn about architectural flow from Foriba systems towards downstream government systems.

**Comment by sovos-foriba-rd** [comment]
Hi Vishant,

You can find code samples for e-delivery note in our GitHub [cloud_sample_api_client_dotnet](url
https://github.com/foriba-rd/cloud_sample_api_client_dotnet) repository. 

If you need more detail about e-Delivery Note (web service methods, doc types etc.) please see the WS API 1.0 documents on this link [https://api.fitbulut.com/#/eIrsaliye](https://api.fitbulut.com/#/eIrsaliye). 

Thanks for your interest and please feel free to contact if you have any other inquiries.

Best regards.
